#!/usr/bin/env python3

"""
NETRA-MAIL Prototype Metrics Calculator

Reads test_results.json generated by test_suite.py
and calculates prototype-level evaluation metrics.

IMPORTANT:
These metrics describe the current 5-scenario prototype test,
not a statistically representative ML benchmark.
"""

import json
import sys
from pathlib import Path


RESULT_FILE = Path("test_results.json")


def load_results(path):
    if not path.exists():
        print(f"ERROR: {path} not found.")
        print("Run:")
        print("    python test_suite.py")
        return None

    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)

        return data

    except json.JSONDecodeError as e:
        print(f"ERROR: Could not parse {path}")
        print(f"JSON error: {e}")
        return None


def extract_cases(data):
    """
    Supports several possible JSON structures generated by
    different versions of the test suite.
    """

    if isinstance(data, list):
        return data

    if not isinstance(data, dict):
        return []

    for key in [
        "results",
        "test_results",
        "cases",
        "tests",
        "scenarios"
    ]:
        value = data.get(key)

        if isinstance(value, list):
            return value

    return []


def get_value(case, keys, default=None):
    for key in keys:
        if key in case:
            return case[key]

    return default


def normalize_expected(value):
    if value is None:
        return ""

    value = str(value).upper().strip()

    if "PHISH" in value:
        return "PHISHING"

    if "SAFE" in value or "LEGIT" in value:
        return "SAFE"

    return value


def normalize_predicted(case):
    value = get_value(
        case,
        [
            "predicted",
            "prediction",
            "predicted_class",
            "classification",
            "risk",
            "risk_level",
            "actual_risk"
        ],
        ""
    )

    if isinstance(value, dict):
        value = (
            value.get("risk")
            or value.get("classification")
            or value.get("label")
            or ""
        )

    return normalize_expected(value)


def normalize_expected_case(case):
    value = get_value(
        case,
        [
            "expected",
            "expected_class",
            "expected_label",
            "ground_truth",
            "label"
        ],
        ""
    )

    return normalize_expected(value)


def calculate_metrics(cases):

    total = len(cases)

    if total == 0:
        print("ERROR: No test cases could be parsed.")
        print()
        print("Make sure you ran:")
        print("    python test_suite.py")
        print()
        print("and that test_results.json contains test results.")
        return

    correct = 0
    phishing_actual = 0
    safe_actual = 0

    phishing_detected = 0
    safe_detected = 0

    true_positive = 0
    true_negative = 0
    false_positive = 0
    false_negative = 0

    print()
    print("=" * 70)
    print("NETRA-MAIL PROTOTYPE METRICS")
    print("=" * 70)

    print()
    print(f"Total test cases: {total}")

    print()
    print("-" * 70)
    print("CASE RESULTS")
    print("-" * 70)

    for i, case in enumerate(cases, start=1):

        expected = normalize_expected_case(case)
        predicted = normalize_predicted(case)

        name = get_value(
            case,
            ["name", "test_name", "scenario"],
            f"Case {i}"
        )

        passed = expected == predicted and expected != ""

        if passed:
            correct += 1

        if expected == "PHISHING":
            phishing_actual += 1

            if predicted == "PHISHING":
                true_positive += 1
                phishing_detected += 1
            elif predicted == "SAFE":
                false_negative += 1

        elif expected == "SAFE":
            safe_actual += 1

            if predicted == "SAFE":
                true_negative += 1
                safe_detected += 1
            elif predicted == "PHISHING":
                false_positive += 1

        status = "PASS" if passed else "FAIL"

        print(
            f"{i}. {name}\n"
            f"   Expected : {expected or 'UNKNOWN'}\n"
            f"   Predicted: {predicted or 'UNKNOWN'}\n"
            f"   Result   : {status}"
        )

    accuracy = correct / total if total else 0

    precision = (
        true_positive / (true_positive + false_positive)
        if (true_positive + false_positive) > 0
        else 0
    )

    recall = (
        true_positive / (true_positive + false_negative)
        if (true_positive + false_negative) > 0
        else 0
    )

    f1 = (
        2 * precision * recall / (precision + recall)
        if (precision + recall) > 0
        else 0
    )

    specificity = (
        true_negative / (true_negative + false_positive)
        if (true_negative + false_positive) > 0
        else 0
    )

    print()
    print("=" * 70)
    print("KEY METRICS")
    print("=" * 70)

    print(f"Accuracy       : {accuracy * 100:.2f}%")
    print(f"Precision      : {precision * 100:.2f}%")
    print(f"Recall         : {recall * 100:.2f}%")
    print(f"F1 Score       : {f1 * 100:.2f}%")
    print(f"Specificity    : {specificity * 100:.2f}%")

    print()
    print("-" * 70)
    print("CONFUSION MATRIX")
    print("-" * 70)

    print(f"True Positive  : {true_positive}")
    print(f"True Negative  : {true_negative}")
    print(f"False Positive : {false_positive}")
    print(f"False Negative : {false_negative}")

    print()
    print("-" * 70)
    print("CLASS DISTRIBUTION")
    print("-" * 70)

    print(f"Actual phishing : {phishing_actual}")
    print(f"Actual safe     : {safe_actual}")
    print(f"Detected phishing: {phishing_detected}")
    print(f"Detected safe    : {safe_detected}")

    print()
    print("=" * 70)

    if correct == total:
        print("RESULT: ALL PROTOTYPE CASES CORRECTLY CLASSIFIED")
    else:
        print(
            f"RESULT: {correct}/{total} prototype cases correctly classified"
        )

    print("=" * 70)

    print()
    print("IMPORTANT:")
    print(
        "These metrics represent the current prototype test suite "
        "and should not be presented as a statistically validated "
        "ML benchmark unless evaluated on a larger independent dataset."
    )

    # Save metrics for presentation/dashboard use
    metrics = {
        "total_cases": total,
        "correct": correct,
        "accuracy": round(accuracy * 100, 2),
        "precision": round(precision * 100, 2),
        "recall": round(recall * 100, 2),
        "f1_score": round(f1 * 100, 2),
        "specificity": round(specificity * 100, 2),
        "true_positive": true_positive,
        "true_negative": true_negative,
        "false_positive": false_positive,
        "false_negative": false_negative,
        "actual_phishing": phishing_actual,
        "actual_safe": safe_actual
    }

    output_file = Path("prototype_metrics.json")

    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(metrics, f, indent=4)

    print()
    print(f"Metrics saved to: {output_file}")


def main():

    path = RESULT_FILE

    # Optional command-line file
    if len(sys.argv) > 1:
        path = Path(sys.argv[1])

    data = load_results(path)

    if data is None:
        sys.exit(1)

    cases = extract_cases(data)

    calculate_metrics(cases)


if __name__ == "__main__":
    main()